checkers:
    # $value == 5;   =>   $value === 5;
    PhpCsFixer\Fixer\Strict\StrictComparisonFixer: ~

    # is_null($value);   =>   null === $value;
    PhpCsFixer\Fixer\LanguageConstruct\IsNullFixer: ~

    # null === $value;   =>   $value === null;
    PhpCsFixer\Fixer\ControlStructure\YodaStyleFixer:
         equal: false

    # in_array('key', $value)   =>   in_array('key', $value, true)
    PhpCsFixer\Fixer\Strict\StrictParamFixer: ~
