# is the class really used somewhere in the package?
name: Check Active Classes

on:
    pull_request: null

env:
    # see https://github.com/composer/composer/issues/9368#issuecomment-718112361
    COMPOSER_ROOT_VERSION: "dev-main"

jobs:
    provide_packages_json:
        # see json juggling: https://docs.github.com/en/free-pro-team@latest/actions/reference/context-and-expression-syntax-for-github-actions#example-6
        runs-on: ubuntu-latest
        steps:
            -   uses: actions/checkout@v2

            -   uses: shivammathur/setup-php@v2
                with:
                    php-version: 8.0
                    coverage: none

            -   uses: "ramsey/composer-install@v1"

            # get package json list
            -
                id: output_data
                run: echo "::set-output name=matrix::$(packages/monorepo-builder/bin/monorepo-builder packages-json --tests)"

        outputs:
            matrix: ${{ steps.output_data.outputs.matrix }}

    check_active_class:
        needs: provide_packages_json

        runs-on: ubuntu-latest

        strategy:
            fail-fast: false
            matrix:
                package: ${{ fromJson(needs.provide_packages_json.outputs.matrix )}}

        name: Check Active Classes in ${{ matrix.package }}

        steps:
            -   uses: actions/checkout@v2

            -   uses: shivammathur/setup-php@v2
                with:
                    php-version: 8.0
                    coverage: none

            -   uses: "ramsey/composer-install@v1"

            -   run: packages/easy-ci/bin/easy-ci check-active-class packages/${{ matrix.package }} --ansi
