name: Daily Pull Requests

on:
    schedule:
        # https://crontab.guru/once-a-day
        -   cron: "0 0 * * *"

jobs:
    daily_pull_requests:
        # Don't run on forks.
        if: github.repository == 'symplify/symplify'

        strategy:
            fail-fast: false
            matrix:
                actions:
                    -
                        name: "Re-Propagate Composer Dependencies to Packages"
                        run: "composer propagate"
                        branch: 'automated-re-propagate-dependencies'

                    -
                        name: "Re-Apply Rector Rules"
                        run: |
                            vendor/bin/rector process --ansi --no-progress-bar --dry-run
                        branch: 'automated-re-apply-rector'

        name: ${{ matrix.actions.name }}

        runs-on: ubuntu-latest

        steps:
            -
                uses: actions/checkout@v2
                with:
                    token: ${{ secrets.ACCESS_TOKEN }}

            # see https://github.com/shivammathur/setup-php
            -
                uses: shivammathur/setup-php@v2
                with:
                    php-version: 8.1
                    coverage: none

            -   uses: "ramsey/composer-install@v1"

            -   run: ${{ matrix.actions.run }}

            # see https://github.com/peter-evans/create-pull-request
            -
                name: Create pull-request
                uses: peter-evans/create-pull-request@v3
                id: cpr
                with:
                    token: ${{ secrets.ACCESS_TOKEN }}
                    commit-message: "[automated] ${{ matrix.actions.name }}"
                    base: 'main'
                    branch: ${{ matrix.actions.branch }}
                    title: '[automated] ${{ matrix.actions.name }}'
                    delete-branch: true

            -
                name: Enable Pull Request Automerge
                if: steps.cpr.outputs.pull-request-operation == 'created'
                uses: peter-evans/enable-pull-request-automerge@v1
                with:
                    token: ${{ secrets.ACCESS_TOKEN }}
                    pull-request-number: ${{ steps.cpr.outputs.pull-request-number }}
                    merge-method: squash
