# inspired at https://github.com/rectorphp/rector/blob/master/.github/workflows/rector_ci.yaml

name: Rector

on:
    pull_request: null

env:
    # see https://github.com/composer/composer/issues/9368#issuecomment-718112361
    COMPOSER_ROOT_VERSION: "dev-main"

jobs:
    rector:
        # run only for repository write-users
        runs-on: ubuntu-latest

        strategy:
            fail-fast: false
            matrix:
                package:
                    - easy-testing
                    - php-config-printer
                    - rule-doc-generator
                    - rule-doc-generator-contracts

        steps:
            -
                if: github.event.pull_request.head.repo.full_name == github.repository
                uses: actions/checkout@v2
                with:
                    # Must be used to trigger workflow after push
                    token: ${{ secrets.ACCESS_TOKEN }}

            # in forks, the token is not available - so we cannot us eit
            -
                 if: github.event.pull_request.head.repo.full_name != github.repository
                 uses: actions/checkout@v2

            -
                uses: shivammathur/setup-php@v2
                with:
                    php-version: 8.1

            -   uses: "ramsey/composer-install@v2"

            -   run: vendor/bin/rector process packages/${{ matrix.package }} --ansi

            # see https://github.com/EndBug/add-and-commit
            -
                # commit only to core contributors who have repository access
                if: github.event.pull_request.head.repo.full_name == github.repository
                uses: EndBug/add-and-commit@v5.1.0
                with:
                    # The arguments for the `git add` command (see the paragraph below for more info)
                    add: .
                    message: "[ci-review] Rector Rectify"
                    # see https://github.community/t/github-actions-bot-email-address/17204
                    author_name: "GitHub Action"
                    author_email: "action@github.com"

                env:
                    # to get push access
                    GITHUB_TOKEN: ${{ secrets.ACCESS_TOKEN }}
