name: Split Tests

on:
    pull_request: null

env:
    # see https://github.com/composer/composer/issues/9368#issuecomment-718112361
    COMPOSER_ROOT_VERSION: "dev-main"

jobs:
    split_tests:
        runs-on: ubuntu-latest

        strategy:
            fail-fast: false

            matrix:
                package:
                    - easy-parallel
                    - easy-testing
                    - php-config-printer
                    - rule-doc-generator
                    - smart-file-system

        name: Split Tests of ${{ matrix.package }}

        steps:
            -   uses: actions/checkout@v2

            -   uses: shivammathur/setup-php@v2
                with:
                    php-version: 8.1
                    coverage: none

            -   uses: "ramsey/composer-install@v2"

            -   run: vendor/bin/monorepo-builder localize-composer-paths packages/${{ matrix.package }}/composer.json --ansi

            -   run: composer update --no-progress --ansi --working-dir packages/${{ matrix.package }}

            -
                working-directory: packages/${{ matrix.package }}
                run: vendor/bin/phpunit
