name: Split Tests

on:
    pull_request: null
    push:
        branches:
            - master

jobs:
    after_split_testing:
        runs-on: ubuntu-latest
        strategy:
            fail-fast: false
            matrix:
                package_name:
                    - autowire-array-parameter
                    - smart-file-system
                    - package-builder
                    - easy-coding-standard
                    - easy-coding-standard-tester
                    - composer-json-manipulator
                    - coding-standard
                    - changelog-linker
                    - monorepo-builder
                    - flex-loader
                    - autodiscovery
                    - set-config-resolver
                    - console-color-diff
                    - easy-hydrator
                    - easy-testing
                    - phpstan-extensions
                    - symfony-static-dumper
                    - skipper

        name: Split Tests of ${{ matrix.package_name }}

        steps:
            -   uses: actions/checkout@v2
            -   uses: shivammathur/setup-php@v1
                with:
                    php-version: 7.3
                    coverage: none
                    # possibly fixes
                    tools: composer:v1

            -   run: composer --version

            -   run: composer update --no-progress --ansi

            -   run: packages/monorepo-builder/bin/monorepo-builder localize-composer-paths packages/${{ matrix.package_name }}/composer.json --ansi

            -
                working-directory: packages/${{ matrix.package_name }}
                run: composer update --no-progress --ansi

            -
                working-directory: packages/${{ matrix.package_name }}
                run: vendor/bin/phpunit
