name: Split Monorepo

on:
    pull_request: null
    push:
        branches:
            - master

jobs:
    monorepo_split_testing:
        runs-on: ubuntu-latest
        strategy:
            matrix:
                actions:
                    -
                        name: monorepo-builder split
                        bar: true
                        run: $MBSCRIPT split

                    -
                        name: monorepo-builder split --verbose
                        bar: true
                        run: $MBSCRIPT split --verbose

                    -
                        name: monorepo-builder split --quiet
                        bar: true
                        run: $MBSCRIPT split --quiet

                    -
                        name: monorepo-builder split --verbose --tag 0.1
                        bar: false
                        run: $MBSCRIPT split --verbose --tag 0.1

        name: Testing ${{ matrix.actions.name }}
        steps:
            -   uses: actions/checkout@v2
            # see https://github.com/shivammathur/setup-php
            -   uses: shivammathur/setup-php@v1
                with:
                    php-version: 7.3
                    coverage: none

            -   name: Configure Git User
                run: |
                  git config --global user.email "tomas.vod@gmail.com"
                  git config --global user.name "Tomas Votruba"

            -   name: Install Composer Dependencies
                run: composer install --no-progress

            -   name: Prepare Sample Monorepo
                run: |
                  rm -rf /tmp/test-monorepo-split
                  mkdir -p /tmp/test-monorepo-split
                  .github/scripts/prepare-test-monorepo.sh /tmp/test-monorepo-split
                  (cd /tmp/test-monorepo-split/monorepo-test-top && git push origin master --tags)

            -   name: Run ${{ matrix.actions.name }}
                run: |
                  (MBSCRIPT=`readlink -f packages/monorepo-builder/bin/monorepo-builder` &&
                   cd /tmp/test-monorepo-split/monorepo-test-top &&
                   ${{ matrix.actions.run }})

            -   name: Verify Split Repositories
                run: |
                  ((cd /tmp/test-monorepo-split &&
                    git clone /tmp/test-monorepo-split/repos/monorepo-test-foo.git monorepo-test-foo &&
                    cd monorepo-test-foo && test -f README.txt) &&
                   if ${{ matrix.actions.bar }}; then
                      (cd /tmp/test-monorepo-split &&
                       git clone /tmp/test-monorepo-split/repos/monorepo-test-bar.git monorepo-test-bar &&
                       cd monorepo-test-bar && test -f README.txt);
                   fi)
